name: Scheduled Deploy to IBM Cloud Foundry

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: init
        run: npm i && npm run build && date
            
      - name: Deploy to IBM Cloud Foundry
        uses: IBM/cloudfoundry-deploy@master
        with:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          IBM_CLOUD_CF_API: ${{ secrets.IBM_CLOUD_CF_API }}
          IBM_CLOUD_CF_ORG: ${{ secrets.IBM_CLOUD_CF_ORG }}
          IBM_CLOUD_CF_SPACE: ${{ secrets.IBM_CLOUD_CF_SPACE }}

  batch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: init
        run: |
             npm i
             npm run build
             cat batch_manifest.yml > manifest.yml
            
      - name: Deploy to IBM Cloud Foundry
        uses: IBM/cloudfoundry-deploy@master
        with:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY2 }}
          IBM_CLOUD_CF_API: ${{ secrets.IBM_CLOUD_CF_API }}
          IBM_CLOUD_CF_ORG: ${{ secrets.IBM_CLOUD_CF_ORG2 }}
          IBM_CLOUD_CF_SPACE: ${{ secrets.IBM_CLOUD_CF_SPACE }}
